version: '3.5'
services:
  # postgres
  db:
    image: postgres:13
    expose:
      - "5432"
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # copy the sql script to create schema
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=test
    networks:
      - default
    restart: always
  dockerfile:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    networks:
      - default
    restart: on-failure
    command: ["sleep","infinity"]
volumes:
  postgres-data: # empty
  
networks:
  default:
    driver: bridge